[phases.setup]
nixPkgs = ["python310", "postgresql"]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate && pip install --upgrade pip",
  ". /opt/venv/bin/activate && pip install -r requirements-railway.txt"
]

[phases.build]
cmds = [
  ". /opt/venv/bin/activate && python manage.py collectstatic --noinput"
]

[start]
cmd = ". /opt/venv/bin/activate && python manage.py migrate && python manage.py ensure_superuser && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 4"
