[phases.setup]
nixPkgs = ["python310", "postgresql"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements-railway.txt"
]

[phases.build]
cmds = [
  "python manage.py collectstatic --noinput"
]

[start]
cmd = "python manage.py migrate && python manage.py ensure_superuser && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 4"
